# Generated by Django 2.0.2 on 2019-11-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='team',
            field=models.CharField(default='', max_length=50),
        ),
    ]
